require python modules at runtime
otherwise we get apache flooding with these errors:

ImportError: No module named traceback
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site.py", line 64, in <module>